import { nanoid } from "nanoid";
import { generateInvestigationAnalysis } from "./ai";
import {
  createInvestigationJob,
  getAlertsByIds,
  getInvestigationByInvestigationId,
  getNextPendingInvestigationJob,
  updateInvestigationByInvestigationId,
  updateInvestigationJob,
} from "../db";
import { buildInvestigationCorrelationContext } from "../correlation";
import { publishRealtimeEvent } from "./realtime";

const WORKER_POLL_MS = 1_000;

let workerTimer: NodeJS.Timeout | null = null;
let workerRunning = false;

const sleep = (ms: number) =>
  new Promise((resolve) => {
    setTimeout(resolve, ms);
  });

const parseReasoningSteps = (reasoning: string): string[] =>
  reasoning
    .split("\n")
    .map((line) => line.trim())
    .filter((line) => line.length > 0);

const extractConfidence = (reasoning: string): number => {
  const confidenceMatch = reasoning.match(/confidence[:\s]+(\d+)/i);
  return confidenceMatch ? parseInt(confidenceMatch[1], 10) / 100 : 0.75;
};

const normalizeAlertIds = (value: unknown): number[] =>
  Array.isArray(value)
    ? value
        .map((item) => (typeof item === "number" ? item : Number(item)))
        .filter((item) => Number.isFinite(item))
    : [];

export async function enqueueInvestigationJob(investigationId: string) {
  const job = await createInvestigationJob({
    id: `JOB-${nanoid(12)}`,
    investigationId,
    status: "pending",
    artifact: null,
  });

  await publishRealtimeEvent({
    type: "investigation.job.queued",
    investigationId,
    jobId: job.id,
    queuedAt: new Date(),
  });

  return job;
}

async function processInvestigationJob(job: Awaited<
  ReturnType<typeof getNextPendingInvestigationJob>
>) {
  if (!job) return;

  await updateInvestigationJob(job.id, {
    status: "running",
    artifact: {
      startedAt: new Date().toISOString(),
    },
  });

  const investigation = await getInvestigationByInvestigationId(job.investigationId);
  if (!investigation) {
    await updateInvestigationJob(job.id, {
      status: "failed",
      artifact: { error: "Investigation not found" },
    });
    return;
  }

  const allowedUserIds = [investigation.userId];

  try {
    await publishRealtimeEvent(
      {
        type: "investigation.step",
        investigationId: investigation.investigationId,
        step: "Collecting evidence from the selected alerts and building the investigation context.",
        index: 0,
        source: "system",
      },
      {
        scope: {
          investigationId: investigation.investigationId,
          allowedUserIds,
        },
      }
    );

    const alertIds = normalizeAlertIds(investigation.alertIds);
    const availableAlerts = await getAlertsByIds(alertIds);
    const alertContext = availableAlerts
      .map(
        (alert) =>
          `Event ${alert.eventId}: ${alert.title} (Severity: ${alert.severity}) from ${alert.source} to ${alert.target ?? "unknown target"}`
      )
      .join("\n");
    const correlationContext = buildInvestigationCorrelationContext(availableAlerts);

    await publishRealtimeEvent(
      {
        type: "investigation.step",
        investigationId: investigation.investigationId,
        step: "Running analysis against the correlated alert context from the background worker.",
        index: 1,
        source: "system",
      },
      {
        scope: {
          investigationId: investigation.investigationId,
          allowedUserIds,
        },
      }
    );

    const analysis = await generateInvestigationAnalysis({
      alerts: availableAlerts,
      alertContext,
      correlationContext,
      onStage: async (stage, index, totalStages) => {
        await publishRealtimeEvent(
          {
            type: "investigation.stage",
            investigationId: investigation.investigationId,
            stage: stage.stage,
            result: stage.result,
            index,
            totalStages,
          },
          {
            scope: {
              investigationId: investigation.investigationId,
              allowedUserIds,
            },
          }
        );
      },
    });

    const reasoning = analysis.text;
    const steps = parseReasoningSteps(reasoning);
    const confidence = extractConfidence(reasoning);
    const totalStepCount = steps.length + 3;

    await publishRealtimeEvent(
      {
        type: "investigation.step",
        investigationId: investigation.investigationId,
        step: analysis.localMode
          ? `Analysis generated in Local Analyst Mode using ${analysis.model}.`
          : analysis.provider === "heuristic"
            ? `AI providers were unavailable, so Sentinel switched to the built-in ${analysis.playbook.playbookId} playbook (${analysis.model}).`
            : `Analysis generated by ${analysis.provider} using ${analysis.model}.`,
        index: 2,
        totalSteps: totalStepCount,
        source: "system",
      },
      {
        scope: {
          investigationId: investigation.investigationId,
          allowedUserIds,
        },
      }
    );

    for (let index = 0; index < steps.length; index += 1) {
      await publishRealtimeEvent(
        {
          type: "investigation.step",
          investigationId: investigation.investigationId,
          step: steps[index],
          index: index + 3,
          totalSteps: totalStepCount,
          source: "analysis",
        },
        {
          scope: {
            investigationId: investigation.investigationId,
            allowedUserIds,
          },
        }
      );
      await sleep(120);
    }

    const completedAt = new Date();
    const artifact = {
      jobId: job.id,
      provider: analysis.provider,
      model: analysis.model,
      localMode: analysis.localMode,
      playbook: analysis.playbook,
      stages: analysis.stages,
      reasoning,
      steps,
      confidence,
      completedAt: completedAt.toISOString(),
    };

    await updateInvestigationByInvestigationId(investigation.investigationId, {
      status: "completed",
      reasoningSteps: steps,
      conclusion: reasoning,
      confidenceScore: confidence.toString() as any,
      completedAt,
    });
    await updateInvestigationJob(job.id, {
      status: "done",
      artifact,
    });

    await publishRealtimeEvent(
      {
        type: "investigation.completed",
        investigationId: investigation.investigationId,
        conclusion: reasoning,
        confidence,
        steps,
        completedAt,
        provider: analysis.provider,
        model: analysis.model,
        localMode: analysis.localMode,
        playbookId: analysis.playbook.playbookId,
        jobId: job.id,
      },
      {
        scope: {
          investigationId: investigation.investigationId,
          allowedUserIds,
        },
      }
    );
  } catch (error) {
    const message =
      error instanceof Error ? error.message : "Investigation failed";
    const failedAt = new Date();

    await updateInvestigationByInvestigationId(investigation.investigationId, {
      status: "failed",
      conclusion: message,
      completedAt: failedAt,
    });
    await updateInvestigationJob(job.id, {
      status: "failed",
      artifact: {
        error: message,
        failedAt: failedAt.toISOString(),
      },
    });

    await publishRealtimeEvent(
      {
        type: "investigation.failed",
        investigationId: investigation.investigationId,
        error: message,
        failedAt,
      },
      {
        scope: {
          investigationId: investigation.investigationId,
          allowedUserIds,
        },
      }
    );
  }
}

async function tickInvestigationWorker() {
  if (workerRunning) return;
  workerRunning = true;

  try {
    const nextJob = await getNextPendingInvestigationJob();
    if (nextJob) {
      await processInvestigationJob(nextJob);
    }
  } finally {
    workerRunning = false;
  }
}

export function startInvestigationWorker() {
  if (workerTimer) {
    return;
  }

  workerTimer = setInterval(() => {
    void tickInvestigationWorker();
  }, WORKER_POLL_MS);

  void tickInvestigationWorker();
}
